---

woken_marathon_id: /woken

woken_config_dir: /srv/docker/woken/config

woken_port: 31087
woken_docker_network: BRIDGE
woken_docker_image_basename: hbpmip/woken
woken_docker_image: "{{ woken_docker_image_basename }}:{{ woken_version }}"

woken_version: latest

analytics_db_port: 31432
analytics_db_host: localhost
analytics_db_user: postgres
analytics_db_password: postgres
analytics_db_jdbc_url: "jdbc:postgresql://{{ analytics_db_host }}:{{ analytics_db_port }}/analytics"
analytics_db_jdbc_driver: "org.postgresql.Driver"
analytics_db_jdbc_jar: "/usr/lib/R/libraries/postgresql-9.4-1201.jdbc41.jar"

ldsm_db_port: 31432
ldsm_db_host: localhost
ldsm_db_user: postgres
ldsm_db_password: postgres
ldsm_db_jdbc_url: "jdbc:postgresql://{{ ldsm_db_host }}:{{ ldsm_db_port }}/analytics"
ldsm_db_jdbc_driver: "org.postgresql.Driver"
ldsm_db_jdbc_jar: "/usr/lib/R/libraries/postgresql-9.4-1201.jdbc41.jar"

# URL to Chronos internal to the current cluster. You need to ensure that the woken application can reach that URL.
internal_chronos_url: http://default:4400

# URL to Marathon master internal to the current cluster. You need to ensure that Ansible can reach that URL.
internal_marathon_url: http://localhost:5080

cluster_role: mip_node
woken_role: "{{ cluster_role }}"

# list of name, url values
woken_nodes: []

# Attach the woken application to a particular host. The hostname should be the name known by Marathon / Mesos
#woken_marathon_host:
woken_main_table: adni_merge
woken_functions:
  - name: boxplot
    docker_image: "hbpmip/r-summary-stats:latest"
  - name: linearregression
    docker_image: "hbpmip/r-linear-regression:latest"
