---

# Deploy data-catalog-db as an independent database. If false, then we assume that there is
# a database already running and we add to it a new 'data-catalog' schema
data_catalog_db_deploy: no

# Used when data_catalog_db_deploy is true
data_catalog_db_marathon_id: /data-factory/data-catalog-db

# Pin the database to a particular host as it needs to store its files in a known place. The hostname should be the name known by Marathon / Mesos
data_catalog_db_marathon_host: '{{ ansible_fqdn }}'

# The user running the Docker container for Postgres, default to '999' (postgres user in the Postgres docker container)
# TODO: use user remapping when this functionality will be available per run (not possible today with Docker 1.12)
data_catalog_db_docker_user: '999'

data_catalog_db_image: 'postgres'
postgres_version: "9.5.4"
data_catalog_db_version: "{{ postgres_version }}"
postgres_is_ready: "/usr/local/bin/pg_isready"
data_catalog_db_is_ready: "{{ postgres_is_ready }}"

data_catalog_db_cpus: 0.5
data_catalog_db_mem: 512.0

# Port exposed by Marathon, must be in the range [4000, 5000[, [31000,32000[
data_catalog_db_port: 4606
data_catalog_db_host: '{{ data_catalog_db_marathon_host }}'
data_catalog_db_name: data_catalog
data_catalog_db_admin_user: postgres
# TO FILL - data_catalog_db_admin_password:
data_catalog_db_user: data_catalog
# TO FILL - data_catalog_db_password: data_catalog

# Hint in Marathon listing all the databases running in this Postgres server,
# used when data_catalog_db_deploy is true
data_catalog_db_databases: "{{ data_catalog_db_name }}"

data_catalog_db_data_dir: /srv/docker/data_catalog_db/data

data_catalog_db_volumes:
  - containerPath: "/var/lib/postgresql/data"
    hostPath: "{{ data_catalog_db_data_dir }}"
    mode: RW

data_catalog_db_env:
  POSTGRES_USER: "{{ data_catalog_db_admin_user }}"
  POSTGRES_PASSWORD: "{{ data_catalog_db_admin_password }}"

# Force cleanup of the data_catalog database. Please never use that in production!
data_catalog_db_cleanup: false

# path to lib_role
data_catalog_db_path_to_lib_role: "{{ lib_roles_path|default(playbook_dir + '/roles') }}"

# URL to marathon master internal to the current cluster. You need to ensure that Ansible can reach that URL.
internal_marathon_url: http://localhost:5080

data_catalog_db_sql_alchemy_conn: "postgresql://{{ data_catalog_db_user }}:{{ data_catalog_db_password }}@{{ data_catalog_db_host }}:{{ data_catalog_db_port }}/data_catalog"

data_catalog_db_setup_image_base: 'hbpmip/data-catalog-setup'
data_catalog_db_setup_version: '1.6.0'
data_catalog_db_setup_image: '{{ data_catalog_db_setup_image_base }}:{{ data_catalog_db_setup_version }}'
