---

- name: Wait for Marathon
  include: ../../marathon-app/tasks/wait-for-marathon.yml
  vars:
    uri: "{{ internal_marathon_url }}"
  tags:
    - launch

- name: Remove old Dev Services DB using Marathon
  marathon_app:
    uri: "{{ internal_marathon_url }}"
    id: "{{ dev_services_db_marathon_id }}"
    state: "absent"
    wait_timeout: 600
  async: 600
  poll: 1
  delegate_to: "{{ groups['control'][0] }}"
  tags:
    - launch

# Postgres user in Docker appears as user 999 outside
- name: Create Dev Services DB storage directory
  file: state=directory path={{ dev_services_db_data_dir }} mode=0700 owner={{ dev_services_db_docker_user }} group={{ dev_services_db_docker_user }}

- name: Launch Dev Services DB using Marathon
  marathon_app:
    uri: "{{ internal_marathon_url }}"
    id: "{{ dev_services_db_marathon_id }}"
    state: "present"
    docker_image: "{{ dev_services_db_image }}:{{ dev_services_db_version }}"
    docker_force_pull_image: true
    docker_network: BRIDGE
    docker_port_mappings:
      - hostPort: '{{ dev_services_db_port }}'
        containerPort: 5432
        name: 'postgres'
        protocol: 'tcp'
    container_volumes:
      - containerPath: "/var/lib/postgresql/data"
        hostPath: "{{ dev_services_db_data_dir }}"
        mode: RW
    env:
      POSTGRES_USER: "{{ dev_services_db_admin_user }}"
      POSTGRES_PASSWORD: "{{ dev_services_db_admin_password }}"
    labels:
      MARATHON_SINGLE_INSTANCE_APP: "true"
      DATABASES: "{{ dev_services_db_databases }}"
    instances: 1
    cpus: '{{ dev_services_db_cpus }}'
    mem: '{{ dev_services_db_mem }}'
    ports: [] # defined in docker_port_mappings
    require_ports: true
    constraints: [["hostname", "CLUSTER", "{{ dev_services_db_marathon_host }}"]]
    dependencies: []
    executor: ""
    health_checks:
      - protocol: COMMAND
        command:
          value: "{{ dev_services_db_is_ready }} -U {{ dev_services_db_admin_user }}"
        gracePeriodSeconds: 300
        intervalSeconds: 20
        timeoutSeconds: 10
        maxConsecutiveFailures: 5
    upgrade_strategy_minimum_health_capacity: 0.0
    upgrade_strategy_maximum_over_capacity: 0.0
    wait_timeout: 600
  async: 600
  poll: 1
  delegate_to: "{{ groups['control'][0] }}"
  tags:
    - launch

- name: Install Python psycopg2 module for Postgres (required by postgresql_db task), pip and curl
  apt: name={{ item }} state=present
  with_items:
    - python-psycopg2
    - python-pip
    - curl
  when: ansible_os_family == 'Debian'
  delegate_to: "{{ groups['control'][0] }}"
  become: True

# run this task on the database host
- name: Wait for the database to be up and running
  wait_for: >
    port="{{ dev_services_db_port }}"
    delay=2

- name: Create a new database with name "gitlab"
  postgresql_db:
    name: "{{ gitlab_db_name }}"
    port: "{{ dev_services_db_port }}"
    login_host: "{{ dev_services_db_host }}"
    login_user: "{{ dev_services_db_admin_user }}"
    login_password: "{{ dev_services_db_admin_password }}"
    state: present
  when: gitlab_db_password is defined
  delegate_to: "{{ groups['control'][0] }}"

- name: Create gitlab user
  postgresql_user:
    login_host: "{{ dev_services_db_host }}"
    login_user: "{{ dev_services_db_admin_user }}"
    login_password: "{{ dev_services_db_admin_password }}"
    db: "{{ gitlab_db_name }}"
    port: "{{ dev_services_db_port }}"
    name: "{{ gitlab_db_user }}"
    password: "{{ gitlab_db_password }}"
    role_attr_flags: "SUPERUSER"
  when: gitlab_db_password is defined
  delegate_to: "{{ groups['control'][0] }}"

- name: Create a new database with name "gitlab_ci"
  postgresql_db:
    name: "{{ gitlab_ci_db_name }}"
    port: "{{ dev_services_db_port }}"
    login_host: "{{ dev_services_db_host }}"
    login_user: "{{ dev_services_db_admin_user }}"
    login_password: "{{ dev_services_db_admin_password }}"
    state: present
  when: gitlab_ci_db_password is defined
  delegate_to: "{{ groups['control'][0] }}"

- name: Create gitlab ci user
  postgresql_user:
    login_host: "{{ dev_services_db_host }}"
    login_user: "{{ dev_services_db_admin_user }}"
    login_password: "{{ dev_services_db_admin_password }}"
    db: "{{ gitlab_ci_db_name }}"
    port: "{{ dev_services_db_port }}"
    name: "{{ gitlab_ci_db_user }}"
    password: "{{ gitlab_ci_db_password }}"
    role_attr_flags: "SUPERUSER"
  when: gitlab_ci_db_password is defined
  delegate_to: "{{ groups['control'][0] }}"

- name: Create a new database with name "sonar"
  postgresql_db:
    name: "{{ sonarqube_db_name }}"
    port: "{{ dev_services_db_port }}"
    login_host: "{{ dev_services_db_host }}"
    login_user: "{{ dev_services_db_admin_user }}"
    login_password: "{{ dev_services_db_admin_password }}"
    state: present
  when: sonarqube_db_password is defined
  delegate_to: "{{ groups['control'][0] }}"

- name: Create sonar user
  postgresql_user:
    login_host: "{{ dev_services_db_host }}"
    login_user: "{{ dev_services_db_admin_user }}"
    login_password: "{{ dev_services_db_admin_password }}"
    db: "{{ sonarqube_db_name }}"
    port: "{{ dev_services_db_port }}"
    name: "{{ sonarqube_db_user }}"
    password: "{{ sonarqube_db_password }}"
    role_attr_flags: "SUPERUSER"
  when: sonarqube_db_password is defined
  delegate_to: "{{ groups['control'][0] }}"
