---

- name: Should meta-db be deployed in its own Postgres server?
  set_fact:
    do_meta_db_deploy: "{{ meta_db_deploy | bool }}"

- include: marathon.yml
  when: do_meta_db_deploy

# run this task on the database host
- name: Wait for the meta database to be up and running
  wait_for: >
    port="{{ meta_db_port }}"
    delay=2

- name: Drop database with name "meta"
  postgresql_db:
    name: "{{ meta_db_name }}"
    port: "{{ meta_db_port }}"
    login_host: "{{ meta_db_host }}"
    login_user: "{{ meta_db_admin_user }}"
    login_password: "{{ meta_db_admin_password }}"
    state: absent
  delegate_to: "{{ groups['control'][0] }}"
  when: (not do_meta_db_deploy) and meta_db_cleanup

- name: Create a new database with name "meta"
  postgresql_db:
    name: "{{ meta_db_name }}"
    port: "{{ meta_db_port }}"
    login_host: "{{ meta_db_host }}"
    login_user: "{{ meta_db_admin_user }}"
    login_password: "{{ meta_db_admin_password }}"
    state: present
  delegate_to: "{{ groups['control'][0] }}"

- name: Create meta user
  postgresql_user:
    login_host: "{{ meta_db_host }}"
    login_user: "{{ meta_db_admin_user }}"
    login_password: "{{ meta_db_admin_password }}"
    db: "{{ meta_db_name }}"
    port: "{{ meta_db_port }}"
    name: "{{ meta_db_user }}"
    password: "{{ meta_db_password }}"
    role_attr_flags: "SUPERUSER"
  delegate_to: "{{ groups['control'][0] }}"

- name: Log into private Docker registries
  docker_login:
    username: '{{ item.username }}'
    password: '{{ item.password }}'
    registry_url: '{{ item.url }}'
  with_items: "{{ meta_db_docker_registries }}"
  no_log: true

- name: Setup Meta database
  docker_container:
    name: setup_meta_db
    image: "{{ item.image }}"
    command: "{{ item.command | default(ommit) }}"
    env: "{{ item.env }}"
    detach: no
    network_mode: host
    interactive: yes
    cleanup: yes
  with_items: "{{ meta_db_docker_setup }}"
  delegate_to: "{{ groups['control'][0] }}"
