- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.7.1
  hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-yaml
-   repo: git://github.com/detailyang/pre-commit-shell
    sha: 1.0.1
    hooks:
    - id: shell-lint
#- repo: https://github.com/willthames/ansible-lint.git
#  sha: v3.3.1
#  hooks:
#    - id: ansible-lint
#      files: \.(yaml|yml)$
