---

- hosts: local
  become: yes
  vars_files:
    - vars/versions.yml
    - vars/settings.yml

# TODO: vim

  pre_tasks:

    - name: Install nitro-powered packages
      apt: name={{item}} state=present
      with_items:
        - sshuttle
      tags:
        - backend_dev
        - sysadmin

    - name: Install dependencies for fish shell
      apt: name={{item}} state=present
      with_items:
        - keychain

    - name: Install some useful Python tools
      pip: name={{item}} state=present
      with_items:
        - ansible-shell
        - ansible-lint
      tags:
        - backend_dev
        - frontend_dev

    - name: Remove old software
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/opt/intellij/idea-IC-141.1532.4/"
        - "/opt/intellij/idea-IC-141.2735.5/"
        - "/opt/intellij/idea-IC-143.381.42/"
        - "/opt/intellij/idea-IC-143.382.35/"
        - "/opt/intellij/idea-IC-143.1184.17/"
        - "/opt/intellij/idea-IC-143.1821.5/"
        - "/opt/intellij/idea-IC-145.597.3/"
        - "/opt/activator/1.3.6/"
      tags:
        - backend_dev
        - frontend_dev
        - algorithms_dev
        - sysadmin

  roles:

    - role: sublimetext
      tags:
        - backend_dev
        - frontend_dev

    - role: intellij
      tags:
        - backend_dev

    - role: activator
      tags:
        - backend_dev

    - role: atom
      tags:
        - backend_dev
        - frontend_dev

    - role: fish
      tags:
        - backend_dev
        - frontend_dev

- hosts: local
  become: no
  vars_files:
    - vars/versions.yml
    - vars/settings.yml
  vars:
    packagecontrol_owner: "{{ ansible_user_id }}"
    packagecontrol_group: "{{ ansible_user_id }}"

  roles:
    - role: sublimetext3-packagecontrol
      tags:
        - backend_dev
        - frontend_dev
