---

- hosts: local
  become: yes
  vars_files:
    - roles/versions.yml
    - vars/settings.yml

# TODO: vim

  roles:
    - role: sublimetext
      tags:
        - backend_dev
        - frontend_dev

    - role: fish
      tags:
        - backend_dev
        - frontend_dev

    - role: intellij
      tags:
        - backend_dev

- hosts: local
  vars_files:
    - roles/versions.yml
    - vars/settings.yml

  roles:
    - role: sublimetext3-packagecontrol
      tags:
        - backend_dev
        - frontend_dev
