---

- hosts: local
  become: yes
  vars_files:
    - vars/versions.yml
    - vars/settings.yml

  pre_tasks:

    - name: Install common packages
      apt: name={{item}} state=present
      with_items:
        - tig
        - git-cola
        - meld
        - curl
        - pgadmin3
        - dos2unix
        - p7zip-full
        - python-setuptools
        - python-pip
        - graphviz
      tags:
        - backend_dev
        - frontend_dev
        - algorithms_dev
        - sysadmin

    - name: Install packages for developers
      apt: name={{item}} state=present
      with_items:
        - subversion
        - git-svn
        - sparkleshare
        - pandoc
        - texlive-fonts-recommended
        - texlive-latex-recommended
        - jq
      tags:
        - backend_dev
        - frontend_dev

    - name: Install packages for backend developers
      apt: name={{item}} state=present
      with_items:
        - virtualbox
      tags:
        - backend_dev
        - sysadmin

    - name: Install packages for system administrator
      apt: name={{item}} state=present
      with_items:
        - pgpgpg
        - ccze # Log colorizer - http://mayurrokade.com/blog/color-highlight-your-logs-with-ccze/
      tags:
        - sysadmin

    # wharfee is a Docker CLI
    - name: Install some useful Python tools
      pip: name={{item}} state=present
      with_items:
        - httpie
        - wharfee
        - pre-commit
      tags:
        - backend_dev
        - frontend_dev
        - algorithms_dev
        - sysadmin

    - name: Install some useful Python tools for system administrator
      pip: name={{item}} state=present
      with_items:
        - ansible-inventory-grapher
      tags:
        - sysadmin

    - name: Download ansible-cmdb
      get_url:
        url: "https://github.com/fboender/ansible-cmdb/releases/download/{{ ansible_cmdb_version }}/ansible-cmdb-{{ ansible_cmdb_version }}.deb"
        dest: "/tmp/ansible-cmdb-{{ ansible_cmdb_version }}.deb"
      tags:
        - sysadmin

    - name: Install ansible-cmdb for Debian family OS
      apt:
        deb: "/tmp/ansible-cmdb-{{ ansible_cmdb_version }}.deb"
      tags:
        - sysadmin

    - name: Remove old software
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /opt/java/oracle/jdk1.8.0_51/
        - /opt/intellij/idea-IC-145.1617.8/
        - /opt/intellij/idea-IC-145.2070.6/
      tags:
        - backend_dev
        - frontend_dev
        - algorithms_dev
        - sysadmin

  roles:

#    - role: soapui
#      tags:
#        - backend_dev
#        - frontend_dev

    - role: docker
      tags:
        - backend_dev
        - frontend_dev
        - algorithms_dev
        - sysadmin
        - docker

    - role: docker-compose
      tags:
        - backend_dev
        - frontend_dev
        - algorithms_dev
        - sysadmin
        - docker-compose

    - role: captain
      tags:
        - backend_dev
        - algorithms_dev
        - sysadmin
        - captain

    - role: java
      tags:
        - backend_dev
        - java

    - role: maven
      tags:
        - backend_dev
        - maven

    - role: sbt-extras
      tags:
        - backend_dev
        - sbt

    - role: nodejs
      tags:
        - backend_dev
        - frontend_dev
        - nodejs

    - role: chrome
      tags:
        - backend_dev
        - frontend_dev
        - chrome

    - role: yed
      tags:
        - backend_dev
        - frontend_dev
        - yed

    - role: vagrant
      tags:
        - backend_dev
        - sysadmin
        - vagrant
