---

- name: Remove old apps from Marathon
  marathon_app:
    uri: "{{ internal_marathon_url }}"
    id: "{{ item }}"
    state: "absent"
  with_items: '{{ old_apps }}'
  ignore_errors: True
  delegate_to: "{{ groups['control'][0] }}"
  run_once: true
