---

# A few good tips for configuring Gitlab in this blog post:
# http://www.mikeobrien.net/blog/setting-up-gitlab-with-active-directory-and-self-signed-cert/

gitlab_version: "7.13.3"

gitlab_host: "{{ inventory_hostname }}"
gitlab_port: 10080
gitlab_https_port: 10443
gitlab_ssh_port: 10022

timezone: "Europe/Zurich"
gitlab_timezone: "Zurich"

#gitlab_external_url: 'http://hbps1.intranet.chuv/git/'

gitlab_default_can_create_group: true
gitlab_username_changing_enabled: true
gitlab_default_theme: 2
gitlab_default_projects_features_issues: true
gitlab_default_projects_features_merge_requests: true
gitlab_default_projects_features_wiki: true
gitlab_default_projects_features_snippets: true
gitlab_default_projects_features_visibility_level: 'private'

gitlab_email: "mip.hbp@gmail.com"
gitlab_email_reply_to: "noreply@chuv.ch"
gitlab_email_display_name: "Gitlab of MIP HBP"

# How to test smtp configuration:
# https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/common_installation_problems/README.md#emails-are-not-being-delivered

gitlab_smtp_enable: true
gitlab_smtp_address: "smtp.gmail.com"
gitlab_smtp_port: 587
gitlab_smtp_user_name:
gitlab_smtp_password:
gitlab_smtp_domain: "smtp.gmail.com"
# One of 'login', 'plain', 'none'
# Use 'none' to disable smtp authentication. gitlab_smtp_user_name and gitlab_smtp_password will not be used
gitlab_smtp_authentication: "login"
gitlab_smtp_enable_starttls_auto: true
gitlab_smtp_tls: false
gitlab_smtp_openssl_verify_mode: 'peer'
gitlab_tls: true

gitlab_enable_lfs: true

# How to check that LDAP configuration is correct:
# sudo gitlab-ctl reconfigure
# sudo gitlab-rake gitlab:ldap:check RAILS_ENV=production

gitlab_enable_ldap: false
gitlab_ldap_server_host:
gitlab_ldap_server_port: 389
gitlab_ldap_uid: "sAMAccountName"
gitlab_ldap_root_dn:
gitlab_ldap_filter:
gitlab_ldap_bind_dn:
gitlab_ldap_bind_password:
gitlab_active_directory: false

gitlab_extra_sign_in_text: |
  |
  ![Company Logo](https://www.humanbrainproject.eu/image/company_logo?img_id=10795&t=1441492532899)
  [Learn more about Human Brain Project](http://www.humanbrainproject.eu/)

#gitlab_extra_sign_in_text: |
#  |
#  ![Company Logo](http://www.unil.ch/webdav/site/lren/shared/lren_logo_small.jpg)
#  [Learn more about LREN](http://www.unil.ch/lren/en/home.html)
