---

- include: base-system.yml

- include: zookeeper.yml

- include: mesos-leader.yml

- include: mesos-mixed.yml

- include: mesos-follower.yml

- include: docker-registry.yml

- include: cleanup.yml

- include: mip-services.yml

- include: analytics-database.yml

- include: denodo.yml

- include: woken.yml

- include: portal-database.yml

- include: meta-database.yml

- include: science-database.yml

- include: portal-backend.yml

- include: portal-frontend.yml

# TODO: delete?
- include: mip-frontend.yml

- include: dev.yml
