---

# Mesos stack

- include: infrastructure/base-system.yml

- include: infrastructure/zookeeper.yml

- include: infrastructure/mesos-leader.yml

- include: infrastructure/mesos-mixed.yml

- include: infrastructure/mesos-follower.yml

# /Mesos stack

- include: infrastructure/cleanup.yml

- include: mip-services.yml

# Reference databases

- include: science-database.yml

- include: denodo.yml

# /Reference databases

# Data Factory

- include: data-factory/airflow.yml

# /Data Factory

# Algorithm Factory

- include: algorithm-factory/analytics-database.yml

- include: algorithm-factory/woken.yml

# /Algorithm Factory

# Web Exploration and Analytics

- include: portal-database.yml

- include: meta-database.yml

- include: portal-backend.yml

- include: portal-frontend.yml

# /Web Exploration and Analytics

- include: dev.yml
