---

- hosts: analytics-db
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  roles:

    - role: postgres
      postgres_marathon_id: /analyticsdb
      postgres_data_dir: /srv/docker/analyticsdb/data
      postgres_port: "{{ analytics_db_port }}"
      postgres_user: "{{ analytics_db_admin_user }}"
      postgres_password: "{{ analytics_db_admin_password }}"
      tags: ['database', 'analytics']

    - role: audit-deployment
      installed_component: analytics-database-server
      tags: ['database', 'analytics']
