---

- hosts: install
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  pre_tasks:
    - name: Install curl
      apt: name=curl state=present
      tags: ['analytics-database', 'database', 'analytics', 'marathon-app']

  roles:

    - role: analytics-database
      tags: ['analytics-database', 'database', 'analytics', 'marathon-app']
    # Audit-deployment delegated to the database host

- hosts: analytics-db
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  roles:

    - role: audit-deployment
      installed_component: analytics-database-content
      tags: ['analytics-database', 'database', 'analytics', 'marathon-app']
