---

- hosts: analytics-db
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  roles:

    # Pin analytics database to the analytics_db host
    - role: postgres
      postgres_marathon_id: "{{ analytics_db_marathon_id }}"
      postgres_marathon_host: "{{ analytics_db_marathon_host }}"
      postgres_data_dir: /srv/docker/analyticsdb/data
      postgres_port: "{{ analytics_db_port }}"
      postgres_user: "{{ analytics_db_admin_user }}"
      postgres_password: "{{ analytics_db_admin_password }}"
      tags: ['analytics-database', 'database', 'analytics', 'marathon-app']

    - role: audit-deployment
      installed_component: analytics-database-server
      tags: ['analytics-database', 'database', 'analytics', 'marathon-app']
