---

# Install Gitlab and launch it with Docker / docker-compose

- hosts: gitlab
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  pre_tasks:
    - name: Install curl
      apt: name=curl state=present
    - name: Install git
      apt: name=git state=present

  roles:

    - role: docker
      tags: ['gitlab']

    - role: docker-compose
      tags: ['gitlab']

    - role: gitlab
      tags: ['gitlab']

    - role: audit-deployment
      installed_component: gitlab
      tags: ['gitlab']
