---

- hosts: mesos-leader
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  pre_tasks:
    - name: Install curl
      apt: name=curl state=present

  roles:

    - role: mesos
      mesos_zk_dns: "{{ groups.zookeeper | join(',') }}"
      mesos_mode: "leader"
      mesos_leaders_group: "mesos-leader"
      tags: ['mesos', 'container-platforms']

    # Java 8 is required for Marathon
    - role: java
      tags: ['mesos-frameworks', 'marathon', 'runtimes']
      when: "'marathon' not in skipped_roles"

    - role: marathon
      tags: ['mesos-frameworks', 'marathon']
      when: "'marathon' not in skipped_roles"

    - role: chronos
      tags: ['mesos-frameworks', 'chronos']
      when: "'chronos' not in skipped_roles"

    - role: audit-deployment
      installed_component: mesos-leader
      tags: ['mesos', 'container-platforms']
