---

- hosts: mip-frontend
  become: yes

  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - ["{{ play_dir }}/vars/{{ datacenter }}-mip-frontend.yml", "{{ play_dir }}/vars/mip-frontend.yml"]
    - "{{ play_dir }}/vars/versions.yml"

  vars:
    #nginx_setup_ssl_certificate: false
    acme_tiny_challenges_directory: '/var/www/letsencrypt'

  pre_tasks:

    - name: Check if Nginx service exists
      stat: path=/etc/init.d/nginx
      register: nginx_service_status

    - name: Delete secure configuration for nginx
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/nginx/conf.d/ssl.conf
        - /etc/nginx/sites-enabled/secured.conf
      when: nginx_service_status.stat.exists

    - name: Restart Nginx if it is already installed
      service: name=nginx state=restarted
      when: nginx_service_status.stat.exists
      ignore_errors: yes

    - name: Create directory for certificates
      file:
        path: "{{ ssl_certs_path }}"
        state: directory
        owner: 'deploy'
        group: 'deploy'
        mode: 0770
      when: nginx_setup_ssl_certificate

  roles:
    - role: php
      when: datacenter == 'federation'
      tags: ['mip-frontend']

    # Quick installation of Nginx to bootstrap Letsencrypt certificate generation
    - role: nginx
      nginx_sites:
        default:
          - |
            listen 80;
            listen [::]:80;
            server_name _;
            root /var/www/html;
            # Let's encrypt challenge
            location '/.well-known/acme-challenge' {
                default_type "text/plain";
                alias {{ acme_tiny_challenges_directory }};
            }
      when: not nginx_service_status.stat.exists and nginx_setup_ssl_certificate
      tags: ['mip-frontend', 'https', 'letsencrypt']

    - role: nginx-letsencrypt-prepare
      when: nginx_setup_ssl_certificate
      tags: ['mip-frontend', 'https', 'letsencrypt']

    - role: letsencrypt
      when: nginx_setup_ssl_certificate
      tags: ['mip-frontend', 'https', 'letsencrypt']

    - role: nginx
      tags: ['mip-frontend']

    - role: services-index
      when: sites_index is defined or services_index is defined
      tags: ['mip-frontend']

# TODO - add a role to oversee deployment of our software
#    - role: portal-frontend
#      tags: ['mip-frontend']

    - role: audit-deployment
      installed_component: mip-frontend
      tags: ['mip-frontend']
