---

- hosts: portal-middleware
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  roles:

    - role: docker-compose

    - role: audit-deployment
      installed_component: portal-middleware
      tags: ['portal', 'middleware']
