---

- hosts: install
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  pre_tasks:
    - name: Install curl
      apt: name=curl state=present
      tags: ['portal-database', 'database', 'portal', 'marathon-app']

  roles:

    - role: portal-database
      tags: ['portal-database', 'database', 'portal', 'marathon-app']
    # Audit-deployment delegated to the database host

- hosts: portal-db
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  roles:

    - role: audit-deployment
      installed_component: portal-database-content
      tags: ['portal-database', 'database', 'portal', 'marathon-app']
