---

- hosts: portal-backend
  become: yes
  gather_facts: no
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  roles:

    - role: portal-backend
      tags: ['portal-backend', 'portal', 'marathon-app']

    - role: audit-deployment
      installed_component: portal-backend
      tags: ['portal-backend', 'portal', 'marathon-app']
