---

- hosts: science-db
  become: yes
  gather_facts: no
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  roles:

    - role: science-database
      tags: ['science-database', 'database', 'portal', 'marathon-app']

    - role: audit-deployment
      installed_component: science-database
      tags: ['science-database', 'database', 'portal', 'marathon-app']
