---

- hosts: managed
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

    - role: first-five-minutes
      tags: ['security']

    - role: unattended-upgrades
      tags: ['security']
