- hosts: install
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  pre_tasks:
    - name: Install curl
      apt: name=curl state=present
      tags: ['woken', 'analytics', 'marathon-app']

  roles:

    - role: woken
      tags: ['woken', 'analytics', 'marathon-app']
    # Audit-deployment delegated to the woken host

- hosts: woken
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  roles:

    - role: audit-deployment
      installed_component: analytics-woken
      tags: ['woken', 'analytics', 'marathon-app']
