---

- name: Should portal-db be deployed in its own Postgres server?
  set_fact:
    do_portal_db_deploy: "{{ portal_db_deploy | bool }}"

- include: marathon.yml
  when: do_portal_db_deploy

# run this task on the database host
- name: Wait for the portal database to be up and running
  wait_for: >
    port="{{ portal_db_port }}"
    delay=2

- name: Drop database with name "portal"
  postgresql_db:
    name: "{{ portal_db_name }}"
    port: "{{ portal_db_port }}"
    login_host: "{{ portal_db_host }}"
    login_user: "{{ portal_db_admin_user }}"
    login_password: "{{ portal_db_admin_password }}"
    state: absent
  delegate_to: "{{ groups['control'][0] }}"
  when: (not do_portal_db_deploy) and portal_db_cleanup

- name: Create a new database with name "portal"
  postgresql_db:
    name: "{{ portal_db_name }}"
    port: "{{ portal_db_port }}"
    login_host: "{{ portal_db_host }}"
    login_user: "{{ portal_db_admin_user }}"
    login_password: "{{ portal_db_admin_password }}"
    state: present
  delegate_to: "{{ groups['control'][0] }}"

- name: Create portal user
  postgresql_user:
    login_host: "{{ portal_db_host }}"
    login_user: "{{ portal_db_admin_user }}"
    login_password: "{{ portal_db_admin_password }}"
    db: "{{ portal_db_name }}"
    port: "{{ portal_db_port }}"
    name: "{{ portal_db_user }}"
    password: "{{ portal_db_password }}"
    role_attr_flags: "SUPERUSER"
  delegate_to: "{{ groups['control'][0] }}"
