---

- name: Should airflow-db be deployed in its own Postgres server?
  set_fact:
    do_airflow_db_deploy: "{{ airflow_db_deploy | bool }}"

- include: marathon.yml
  when: do_airflow_db_deploy

# run this task on the database host
- name: Wait for the database to be up and running
  wait_for: >
    port="{{ airflow_db_port }}"
    delay=2

- name: Drop database with name "airflow"
  postgresql_db:
    name: "{{ airflow_db_name }}"
    port: "{{ airflow_db_port }}"
    login_host: "{{ airflow_db_host }}"
    login_user: "{{ airflow_db_admin_user }}"
    login_password: "{{ airflow_db_admin_password }}"
    state: absent
  delegate_to: "{{ groups['control'][0] }}"
  when: (not do_airflow_db_deploy) and airflow_db_cleanup

- name: Create a new database with name "airflow"
  postgresql_db:
    name: "{{ airflow_db_name }}"
    port: "{{ airflow_db_port }}"
    login_host: "{{ airflow_db_host }}"
    login_user: "{{ airflow_db_admin_user }}"
    login_password: "{{ airflow_db_admin_password }}"
    state: present
  delegate_to: "{{ groups['control'][0] }}"

- name: Create airflow user
  postgresql_user:
    login_host: "{{ airflow_db_host }}"
    login_user: "{{ airflow_db_admin_user }}"
    login_password: "{{ airflow_db_admin_password }}"
    db: "{{ airflow_db_name }}"
    port: "{{ airflow_db_port }}"
    name: "{{ airflow_db_user }}"
    password: "{{ airflow_db_password }}"
    role_attr_flags: "SUPERUSER"
  delegate_to: "{{ groups['control'][0] }}"
