---

- hosts: portal-frontend
  become: yes
  gather_facts: no
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  roles:

    - role: portal-frontend
      tags: ['portal-frontend', 'portal', 'marathon-app']

    - role: audit-deployment
      installed_component: portal-frontend
      tags: ['portal-frontend', 'portal', 'marathon-app']
