---

version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: hbpmip/ubuntu-for-ci:16.04-1
    environment:
       - CIRCLECI: true
    steps:
      - checkout
      - run:
          name: "Initialise Git submodules and Git hooks"
          command: |
            ./after-git-clone.sh
            ./after-update.sh
            cp -R /root/src /home/tester/
            chown -R tester:tester /home/tester
      - run:
          name: "Validate code quality"
          command: |
            pre-commit run --all-files
      - run:
          name: "Test setup"
          command: |
            ./common/scripts/bootstrap.sh --skip-git-crypt
      - run:
          name: "Test standard instalation"
          command: |
            ./setup.sh All Standard skip_docker skip_yed
      - run:
          name: "Test tester installation"
          command: |
            gosu tester /bin/bash -c "CIRCLECI=true USER=tester /home/tester/src/setup.sh All Hipster"
