---

version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: ubuntu:16.04
    environment:
       - CIRCLECI: true
    steps:
      - checkout
      - run:
          name: "Install requirements"
          command: |
            apt-get update
            apt-get install -y sudo shellcheck python-pip
            perl -p -i -e 's/%sudo\s*ALL=\(ALL:ALL\) ALL/%sudo ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
            adduser --quiet --system --disabled-password --ingroup sudo hipster
            ./common/scripts/bootstrap.sh --skip-git-crypt
            pip install pre-commit ansible-lint
            mkdir -p ~/Desktop
      - run:
          name: "Initialise Git submodules and Git hooks"
          command: |
            ./after-git-clone.sh
            ./after-update.sh
      - run:
          name: "Validate code quality"
          command: |
            pre-commit run --all-files
      - run:
          name: "Test setup"
          command: |
            ./common/scripts/bootstrap.sh --skip-git-crypt
      - run:
          name: "Test standard instalation"
          command: |
            ./setup.sh All Standard skip_docker skip_yed
      - run:
          name: "Test hipster installation"
          command: |
            sudo -u hipster ./setup.sh All Hipster
