---

- name: Should mipmap-db be deployed in its own Postgres server?
  set_fact:
    do_mipmap_db_deploy: "{{ mipmap_db_deploy | bool }}"

- include: marathon.yml
  when: do_mipmap_db_deploy

# run this task on the database host
- name: Wait for the mipmap database to be up and running
  wait_for: >
    port="{{ mipmap_db_port }}"
    delay=2

- name: Drop database with name "mipmap"
  postgresql_db:
    name: "{{ mipmap_db_name }}"
    port: "{{ mipmap_db_port }}"
    login_host: "{{ mipmap_db_host }}"
    login_user: "{{ mipmap_db_admin_user }}"
    login_password: "{{ mipmap_db_admin_password }}"
    state: absent
  delegate_to: "{{ groups['control'][0] }}"
  when: (not do_mipmap_db_deploy) and mipmap_db_cleanup

- name: Create a new database with name "mipmap"
  postgresql_db:
    name: "{{ mipmap_db_name }}"
    port: "{{ mipmap_db_port }}"
    login_host: "{{ mipmap_db_host }}"
    login_user: "{{ mipmap_db_admin_user }}"
    login_password: "{{ mipmap_db_admin_password }}"
    state: present
  delegate_to: "{{ groups['control'][0] }}"

- name: Create mipmap user
  postgresql_user:
    login_host: "{{ mipmap_db_host }}"
    login_user: "{{ mipmap_db_admin_user }}"
    login_password: "{{ mipmap_db_admin_password }}"
    db: "{{ mipmap_db_name }}"
    port: "{{ mipmap_db_port }}"
    name: "{{ mipmap_db_user }}"
    password: "{{ mipmap_db_password }}"
    role_attr_flags: "SUPERUSER"
  delegate_to: "{{ groups['control'][0] }}"

- name: Create configuration folder for MipMap
  file:
    path: '/etc/mipmap'
    state: directory

- name: Store the configuration for MipMap
  template:
    src: 'postgresdb.properties.j2'
    dest: '{{ mipmap_db_config_file }}'
