---

docker_registry_config_orig_dir: envs/federation-dev
# Registry on QA (hbpfedqa1)
docker_registry_ip: 155.105.223.23
docker_registry_dns: registry.federation.mip.hbp

packagecontrol_packages:
  - "GitGutter"
  - "Terminal"
  - "Ansible"
  - "Dockerfile Syntax Highlighting"

fish_completions:
  - 'composer'

fish_users:
  - "{{ ansible_user_id }}"