---

docker_registry_config_orig_dir: envs/federation-dev
# Registry on QA (hbpfedqa1)
docker_registry_ip: 155.105.223.23
docker_registry_dns: registry.federation.mip.hbp

sublimetext_dl_source: "https://download.sublimetext.com"

packagecontrol_packages:
  - "GitGutter"
  - "Terminal"
  - "Ansible"
  - "Dockerfile Syntax Highlighting"

atom_packages:
  - atom-beautify
  - autoclose-html
  - highlight-selected
  - language-babel
  - language-ansible
  - language-docker
  - linter
  - linter-eslint
  - linter-ansible-linting
  - linter-docker
  - autocomplete-ansible
  - minimap
  - minimap-highlight-selected
  - pigments
  - seti-ui
  - monokai-seti
  - activate-power-mode
  - git-time-machine
  - language-matlab
  - gitlab
  - autocomplete-plus
  - project-manager
  - find-and-replace
  - markdown-preview

atom_user: '{{ user }}'
atom_desktop_icon: true

fish_completions:
  - 'apt-get'
  - 'chmod'
  - 'chown'
  - 'composer'
  - 'cp'
  - 'date'
  - 'dpkg'
  - 'echo'
  - 'env'
  - 'eval'
  - 'exec'
  - 'git'
  - 'grep'
  - 'grunt'
  - 'head'
  - 'mv'
  - 'mvn'
  - 'node'
  - 'ping'
  - 'ps'
  - 'python'
  - 'python2'
  - 'python3'
  - 'ssh'
  - 'stat'
  - 'sudo'
  - 'svn'
  - 'tail'
  - 'tee'
  - 'top'
  - 'vagrant'
  - 'vi'
  - 'vim'
#  - 'docker'

fish_users:
  - "{{ ansible_user_id }}"
