---

docker_registry_config_orig_dir: envs/federation-dev
# Registry on QA (hbpfedqa1)
docker_registry_ip: 155.105.223.23
docker_registry_dns: registry.federation.mip.hbp

packagecontrol_packages:
  - "GitGutter"
  - "Terminal"
  - "Ansible"
  - "Dockerfile Syntax Highlighting"

fish_completions:
  - 'apt-get'
  - 'chmod'
  - 'chown'
  - 'composer'
  - 'cp'
  - 'date'
  - 'docker'
  - 'dpkg'
  - 'echo'
  - 'env'
  - 'eval'
  - 'exec'
  - 'git'
  - 'grep'
  - 'grunt'
  - 'head'
  - 'mv'
  - 'mvn'
  - 'node'
  - 'ping'
  - 'ps'
  - 'python'
  - 'python2'
  - 'python3'
  - 'ssh'
  - 'stat'
  - 'sudo'
  - 'svn'
  - 'tail'
  - 'tee'
  - 'top'
  - 'vagrant'
  - 'vi'
  - 'vim'

fish_users:
  - "{{ ansible_user_id }}"