---

docker_registry_config_orig_dir: envs/federation-dev
docker_registry_ip: 155.105.202.126
docker_registry_dns: registry.federation.mip.hbp

packagecontrol_packages:
  - "GitGutter"
  - "Terminal"
  - "Ansible"
  - "Dockerfile Syntax Highlighting"

fish_completions:
  - 'composer'

fish_users:
  - "{{ ansible_user_id }}"