---
# Invariants for Zookeeper and Zookeeper users

# TODO: rename in zookeeper role
client_port: '{{ zookeeper_port }}'

zookeeper_hosts: "
  {%- set zk_hosts = [] -%}
  {%- for host in groups[zookeeper_server_group]|sort -%}
    {%- set zk_hosts = zk_hosts + [{ 'host': hostvars[host].ip_address, 'id': loop.index}] -%}
  {%- endfor -%}
  {{ zk_hosts }}
"

# TODO: move to zookeeper role?
zookeeper_id: "
  {%- if zk_id is defined -%}
    {{ zk_id }}
  {%- else -%}
    {%- for host in groups[zookeeper_server_group]|sort -%}
      {%- if host == 'default' or host == inventory_hostname or host == inventory_hostname_short or host == ansible_fqdn or host in ansible_all_ipv4_addresses -%}
        {{ loop.index }}
      {%- endif -%}
    {%- endfor -%}
  {%- endif -%}
"
