---

dev_services_db_marathon_id: /dev-services/dev-services-db

# Attach the Postgres database to a particular host. The hostname should be the name known by Marathon / Mesos
dev_services_db_marathon_host: '{{ inventory_hostname }}'

# The user running the Docker container for Postgres, default to '999' (postgres user in the Postgres docker container)
# TODO: use user remapping when this functionality will be available per run (not possible today with Docker 1.12)
dev_services_db_docker_user: '999'

postgres_version: "9.5.3"

dev_services_db_cpus: 0.5
dev_services_db_mem: 512.0

# Port exposed by Marathon, must be in the range [31000,32000[
dev_services_db_port: 31532
dev_services_db_host: localhost
dev_services_db_admin_user: postgres
# TO FILL - dev_services_db_admin_password:

gitlab_db_database: "gitlab"
gitlab_db_user: "gitlab"
# TO FILL - gitlab_db_password:

gitlab_ci_db_database: "gitlab_ci"
gitlab_ci_db_user: "gitlab_ci"
# TO FILL - gitlab_ci_db_password:

sonarqube_db_database: "sonar"
sonarqube_db_user: "sonar"
# TO FILL - sonarqube_db_password:

dev_services_db_data_dir: /srv/docker/meta-db/data

dev_services_db_setup_dir: /opt/meta-database/migration

# URL to marathon master internal to the current cluster. You need to ensure that Ansible can reach that URL.
internal_marathon_url: http://localhost:5080
