---

airflow_db_marathon_id: /airflow/db
airflow_mysql_marathon_id: '{{ airflow_db_marathon_id }}'

airflow_mysql_data_dir: /srv/docker/airflow_db/data
# The user running the Docker container for mysql, default to '999' (mysql user in the mysql docker container)
airflow_mysql_docker_user: '999'

# Pin the database to a particular host as it needs to store its files in a known place
airflow_mysql_marathon_host: '{{ inventory_hostname }}'
# Port exposed by Marathon, must be in the range [4000, 5000[, [31000,32000[
airflow_mysql_port: 4306

mysql_version: "5.7.12"

#airflow_mysql_root_password:

airflow_mysql_user: airflow
airflow_mysql_password: airflow

airflow_mysql_mem: 368.0

# URL to marathon master internal to the current cluster. You need to ensure that Ansible can reach that URL.
internal_marathon_url: http://localhost:5080

# Attach the mysql database to a particular host. The hostname should be the name known by Marathon / Mesos
#mysql_marathon_host:
