---

- name: Install Python psycopg2 module
  apt: name=python-psycopg2 state=present
  when: ansible_os_family == 'Debian'
  delegate_to: "{{ analytics_db_host }}"

- name: Wait for the database to be up and running
  wait_for: >
    port="{{ analytics_db_port }}"
    delay=5
  delegate_to: "{{ analytics_db_host }}"

- name: Create a new database with name "analytics"
  postgresql_db:
    name: analytics
    port: "{{ analytics_db_port }}"
    login_host: "{{ analytics_db_host }}"
    login_user: "{{ analytics_db_admin_user }}"
    login_password: "{{ analytics_db_admin_password }}"
    state: present
  delegate_to: "{{ analytics_db_host }}"

- name: Create analytics user
  postgresql_user:
    login_host: "{{ analytics_db_host }}"
    login_user: "{{ analytics_db_admin_user }}"
    login_password: "{{ analytics_db_admin_password }}"
    db: analytics
    port: "{{ analytics_db_port }}"
    name: "{{ analytics_db_user }}"
    password: "{{ analytics_db_password }}"
    role_attr_flags: "SUPERUSER"
  delegate_to: "{{ analytics_db_host }}"

- name: Create setup dir
  file: 
    state: directory
    path: "{{analytics_db_setup_dir}}"

- name: Copy sql creation scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{analytics_db_setup_dir}}/{{ item.dest }}"
  with_items:
   - src: "analyticsdb/sql/create.sql"
     dest: "V1_0__Create-result-table.sql"

- name: Run Flyway migration
  command: "flyway -url={{analytics_db_jdbc_url}} -user={{ analytics_db_user }} -password={{ analytics_db_password }} -locations=filesystem:{{analytics_db_setup_dir}} migrate"
