---
#
# Master Install
#
# Installs _the_ world
#

- include: ../../common/playbooks/infrastructure/setup.yml

- include: ../../common/playbooks/data-factory/setup.yml

- hosts: airflow-agent
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/data-factory/endpoints.yml"
    - "{{ play_dir }}/vars/data-factory/airflow.yml"

  tasks:

    - name: Create group for Airflow
      group:
        name: '{{ airflow_group }}'
        state: present
      tags:
        - demo

    - name: Create user for Airflow
      user:
        name: '{{ airflow_user }}'
        group: '{{ airflow_group }}'
        home: '{{ airflow_home }}'
      tags:
        - demo

    - name: Create folders for data and scripts
      file: path='{{ item }}' state=directory owner=airflow
      with_items:
        - /data/input/demo
        - /data/input/ehr_demo
      tags:
        - demo

    - name: Get some MRI data from public datasets (it takes time)
      git:
        repo: https://github.com/dcunited001/mri-scans.git
        version: master
        dest: /data/input/demo
        depth: 1
      tags:
        - demo

    - name: Get some demo EHR data from Git
      git:
        repo: https://github.com/HBPMedical/MIPMap-demo-ehr-to-i2b2.git
        version: master
        dest: /tmp/MIPMap-demo-ehr-to-i2b2
        depth: 1
      tags:
        - demo

    # Using rsync as synchronise seems to have trouble with Vagrant
    - name: Put the demo EHR data into the input folder
      command: >
        rsync -av /tmp/MIPMap-demo-ehr-to-i2b2/source/ /data/ehr_demo/
      tags:
        - demo
        - skip_ansible_lint

- hosts: cbrain
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    #- "{{ play_dir }}/vars/cbrain.yml"

  roles:

    - role: cbrain-database
      tags: ['cbrain']

    - role: cbrain-portal
      tags: ['cbrain']

    - role: cbrain-data-provider
      tags: ['cbrain']

    - role: cbrain-bourreau
      tags: ['cbrain']

    - role: audit-deployment
      installed_component: cbrain
      tags: ['cbrain']
