---
#
# Master Install
#
# Installs _the_ world
#

- include: ../../common/playbooks/base-system.yml

- include: ../../common/playbooks/zookeeper.yml

- include: ../../common/playbooks/mesos-leader.yml

- include: ../../common/playbooks/mesos-mixed.yml

- include: ../../common/playbooks/mesos-follower.yml

- hosts: airflow
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/airflow.yml"

  pre_tasks:

    - name: Setup Matlab library for Python
      command: python ./setup.py install
      args:
        chdir: /usr/local/MATLAB/R2015b/extern/engines/python
      tags: ['airflow', 'matlab']

  roles:

#    - role: airflow-database
#      tags: ['airflow']
#
#    - role: mri-database
#      tags: ['airflow']
#
#    - role: airflow
#      tags: ['airflow']

    - role: audit-deployment
      installed_component: airflow
      tags: ['airflow']

- hosts: cbrain
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    #- "{{ play_dir }}/vars/cbrain.yml"

  roles:

    - role: cbrain-database
      tags: ['cbrain']

    - role: cbrain-portal
      tags: ['cbrain']

    - role: cbrain-data-provider
      tags: ['cbrain']

    - role: cbrain-bourreau
      tags: ['cbrain']

    - role: audit-deployment
      installed_component: cbrain
      tags: ['cbrain']
