---

# Version of the Docker image for PostgresRAW UI to use
postgresraw_ui_image: 'hbpmip/postgresraw-ui'
postgresraw_ui_version: latest

# Id of PostgresRAW UI in Marathon
postgresraw_ui_marathon_id: /hospital-database/postgresraw-ui

# Attach PostgresRAW UI to a particular host. The hostname should be the name known by Marathon / Mesos
postgresraw_ui_marathon_host: '{{ ansible_fqdn }}'
# Set of constraints to use to place PostgresRAW UI on some particular host(s)
postgresraw_ui_marathon_constraints: [["hostname", "CLUSTER", "{{ postgresraw_ui_marathon_host | trim }}"]]
# Number of instances of PostgresRAW UI to launch
postgresraw_ui_instances: 1

postgresraw_ui_admin_port: 31555

# Amount of CPU reserved for PostgresRAW UI
postgresraw_ui_cpus: 1.0
# Amount of memory in mb reserved for PostgresRAW UI
postgresraw_ui_mem: 100.0

# Additional parameters for Docker
postgresraw_ui_docker_parameters: []

postgresraw_ui_postgres_host: '{{ ldsm_db_host }}'
postgresraw_ui_postgres_port: '{{ ldsm_db_port }}'
postgresraw_ui_postgres_user: '{{ ldsm_db_user }}'
postgresraw_ui_postgres_password: '{{ ldsm_db_password }}'
postgresraw_ui_postgres_db: '{{ ldsm_db_name }}'
postgresraw_ui_pg_data_folder: '{{ ldsm_db_data_dir }}'
postgresraw_ui_raw_data_folder: '{{ ldsm_db_raw_data_dir }}'

postgresraw_ui_env:
  POSTGRES_HOST: "{{ postgresraw_ui_postgres_host }}"
  POSTGRES_PORT: "{{ postgresraw_ui_postgres_port }}"
  POSTGRES_USER: "{{ postgresraw_ui_postgres_user }}"
  POSTGRES_PASSWORD: "{{ postgresraw_ui_postgres_password }}"
  POSTGRES_DB: "{{ postgresraw_ui_postgres_db }}"

postgresraw_ui_dependencies: ["{{ ldsm_db_marathon_id }}"]
