---

chronos_marathon_id: /algorithm-factory/chronos

chronos_port: 4400
chronos_docker_image_basename: mesoscloud/chronos
chronos_docker_image: "{{ chronos_docker_image_basename }}:{{ chronos_version }}"

chronos_version: "2.4.0-ubuntu-14.04"

chronos_zk_mesos_master: 'zk://node-1:2181,node-2:2181,node-3:2181/mesos'
chronos_zk_hosts: 'node-1:2181,node-2:2181,node-3:2181'
chronos_failure_retry: 5000
chronos_disable_after_failures: 1
chronos_cluster_name: '{{ mesos_cluster }}'
chronos_cpus: 0.5
chronos_mem: 512.0
chronos_docker_parameters: []
