---

- hosts: research-db,research-database
  become: yes
  gather_facts: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/mesos.yml"
    - "{{ play_dir }}/vars/reference/endpoints.yml"
    - "{{ play_dir }}/vars/reference/research-database.yml"

  pre_tasks:

  - name: Setup standard research datasets
    include_vars: "{{ play_dir }}/vars/reference/standard-research-datasets.yml"
    when: setup_standard_research_datasets | default(false)
    tags: ['research-database', 'research-db', 'database', 'reference', 'marathon-app']

  - name: Add standard research datasets to research database setup
    set_fact:
      research_db_docker_setup: "{{ standard_research_db_docker_setup | union(research_db_docker_setup | default([])) }}"
    when: setup_standard_research_datasets | default(false)
    tags: ['research-database', 'research-db', 'database', 'reference', 'marathon-app']

  roles:

    - role: research-database
      tags: ['research-database', 'research-db', 'database', 'reference', 'marathon-app']

    - role: audit-deployment
      installed_component: reference-research-database
      tags: ['research-database', 'research-db', 'database', 'reference', 'marathon-app']
