---

- hosts: research-db,research-database
  become: yes
  gather_facts: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/mesos.yml"
    - "{{ play_dir }}/vars/reference/endpoints.yml"
    - "{{ play_dir }}/vars/reference/research-database.yml"

  roles:

    - role: research-database
      tags: ['research-database', 'research-db', 'database', 'reference', 'marathon-app']

    - role: audit-deployment
      installed_component: reference-research-database
      tags: ['research-database', 'research-db', 'database', 'reference', 'marathon-app']
