---

# Deploy i2b2-capture-db as an independent database. If false, then we assume that there is
# a database already running and we add to it a new 'i2b2_capture' schema
i2b2_capture_db_deploy: no

# Used when i2b2_capture_db_deploy is true
i2b2_capture_db_marathon_id: /data-factory/i2b2-capture-db

# Pin the database to a particular host as it needs to store its files in a known place. The hostname should be the name known by Marathon / Mesos
i2b2_capture_db_marathon_host: '{{ ansible_fqdn }}'

# The user running the Docker container for Postgres, default to '999' (postgres user in the Postgres docker container)
# TODO: use user remapping when this functionality will be available per run (not possible today with Docker 1.12)
i2b2_capture_db_docker_user: '999'

i2b2_capture_db_image: 'postgres'
postgres_version: "9.5.4"
i2b2_capture_db_version: "{{ postgres_version }}"
postgres_is_ready: "/usr/local/bin/pg_isready"
i2b2_capture_db_is_ready: "{{ postgres_is_ready }}"

i2b2_capture_db_cpus: 0.5
i2b2_capture_db_mem: 512.0

# Port exposed by Marathon, must be in the range [4000, 5000[, [31000,32000[
i2b2_capture_db_port: 4606
i2b2_capture_db_host: '{{ i2b2_capture_db_marathon_host }}'
i2b2_capture_db_name: i2b2_capture
i2b2_capture_db_admin_user: postgres
# TO FILL - i2b2_capture_db_admin_password:
i2b2_capture_db_user: i2b2_capture
# TO FILL - i2b2_capture_db_password: i2b2

# Hint in Marathon listing all the databases running in this Postgres server,
# used when i2b2_capture_db_deploy is true
i2b2_capture_db_databases: "{{ i2b2_capture_db_name }}"

i2b2_capture_db_data_dir: /srv/docker/i2b2_capture_db/data

i2b2_capture_db_volumes:
  - containerPath: "/var/lib/postgresql/data"
    hostPath: "{{ i2b2_capture_db_data_dir }}"
    mode: RW

i2b2_capture_db_env:
  POSTGRES_USER: "{{ i2b2_capture_db_admin_user }}"
  POSTGRES_PASSWORD: "{{ i2b2_capture_db_admin_password }}"

# Force cleanup of the i2b2 capture DB. Please never use that in production!
i2b2_capture_db_cleanup: false

# path to lib_role
i2b2_capture_db_path_to_lib_role: "{{ lib_roles_path|default(playbook_dir + '/roles') }}"

# URL to marathon master internal to the current cluster. You need to ensure that Ansible can reach that URL.
internal_marathon_url: http://localhost:5080

i2b2_capture_db_sql_alchemy_conn: "postgresql://{{ i2b2_capture_db_user }}:{{ i2b2_capture_db_password }}@{{ i2b2_capture_db_host }}:{{ i2b2_capture_db_port }}/{{ i2b2_capture_db_name }}"

i2b2_capture_db_setup_image_base: 'hbpmip/i2b2-setup'
i2b2_capture_db_setup_version: '1.4.6'
i2b2_capture_db_setup_image: '{{ i2b2_capture_db_setup_image_base }}:{{ i2b2_capture_db_setup_version }}'
