---

# Version of the Docker image for Portal backend to use
portal_backend_version: latest

# Id of Portal backend in Marathon
portal_backend_marathon_id: /portal/portal-backend

# Attach Portal backend to a particular host. The hostname should be the name known by Marathon / Mesos
portal_backend_marathon_host: '{{ inventory_hostname }}'
# Set of constraints to use to place Portal backend on some particular host(s)
portal_backend_marathon_constraints: [["hostname", "CLUSTER", "{{ portal_backend_marathon_host }}"]]
# Number of instances of Portal backend to launch
portal_backend_instances: 1

# Amount of CPU reserved for Portal backend
portal_backend_cpus: 1.0
# Amount of memory in mb reserved for Portal backend
portal_backend_mem: 2048.0

# Port to use to expose Portal backend to other services in the cluster.
portal_backend_port: 4080
portal_backend_akka_port: 4089
# Prefix path for all services provided by Portal backend
portal_backend_context_path: ""
portal_backend_session_timeout: 2592000
portal_backend_logging_level_web: "DEBUG"
portal_backend_logging_level_hibernate: "DEBUG"
portal_backend_frontend_after_login_url: 'http://{{ portal_backend_marathon_host }}:{{ portal_backend_port }}/home'
# Additional parameters for Docker
portal_backend_docker_parameters: []

portal_db_port: 31432
portal_db_host: localhost
portal_db_user: portal
portal_db_password: portal-db
portal_db_jdbc_url: "jdbc:postgresql://{{ portal_db_host }}:{{ portal_db_port }}/{{ portal_db_user }}"
portal_db_jdbc_driver: "org.postgresql.Driver"
portal_db_marathon_id: "/frontend/portal-db"

meta_db_port: 31432
meta_db_host: localhost
meta_db_user: meta
meta_db_password: meta-db
meta_db_jdbc_url: "jdbc:postgresql://{{ meta_db_host }}:{{ meta_db_port }}/{{ meta_db_user }}"
meta_db_jdbc_driver: "org.postgresql.Driver"
meta_db_marathon_id: "/frontend/meta-db"

science_db_port: 31433
science_db_host: localhost
science_db_user: science
science_db_password: science-db
science_db_jdbc_url: "jdbc:postgresql://{{ science_db_host }}:{{ science_db_port }}/{{ science_db_user }}"
science_db_jdbc_driver: "org.postgresql.Driver"
science_db_marathon_id: "/frontend/science-db"

portal_backend_security_enabled: false

#portal_backend_hbp_client_id:
#portal_backend_hbp_client_secret:
portal_backend_hbp_access_token_uri: "https://services.humanbrainproject.eu/oidc/token"
portal_backend_hbp_user_authorization_uri: "https://services.humanbrainproject.eu/oidc/authorize"
portal_backend_hbp_user_info_uri: "https://services.humanbrainproject.eu/oidc/userinfo"

woken_host: 'localhost'
woken_port: '8088'
woken_path: '/user/entrypoint'
internal_woken_url: 'http://localhost:8087'

portal_backend_exareme_url: 'http://hbps2.chuv.ch:9090'

portal_backend_env:
  PORTAL_DB_URL: "{{ portal_db_jdbc_url }}"
  PORTAL_DB_SCHEMA: "public"
  PORTAL_DB_USER: "{{ portal_db_user }}"
  PORTAL_DB_PASSWORD: "{{ portal_db_password }}"
  META_DB_URL: "{{ meta_db_jdbc_url }}"
  META_DB_SCHEMA: "public"
  META_DB_USER: "{{ meta_db_user }}"
  META_DB_PASSWORD:  "{{ meta_db_password }}"
  SCIENCE_DB_URL: "{{ science_db_jdbc_url }}"
  SCIENCE_DB_SCHEMA: "public"
  SCIENCE_DB_MAIN_TABLE: "adni_merge"
  SCIENCE_DB_USER: "{{ science_db_user }}"
  SCIENCE_DB_PASSWORD: "{{ science_db_password }}"
  AUTHENTICATION: 0
  LOGGING_LEVEL_WEB: '{{ portal_backend_logging_level_web }}'
  LOGGING_LEVEL_HIBERNATE: '{{ portal_backend_logging_level_hibernate }}'
  CONTEXT_PATH: '{{ portal_backend_context_path }}'
  SESSION_TIMEOUT: '{{ portal_backend_session_timeout }}'
  WOKEN_URL: '{{ internal_woken_url }}'
  EXAREME_URL: '{{ portal_backend_exareme_url }}'
  FRONTEND_AFTER_LOGIN_URL: '{{ portal_backend_frontend_after_login_url }}'
  WOKEN_HOST: '{{ woken_host }}'
  WOKEN_PORT: '{{ woken_port }}'
  WOKEN_PATH: '{{ woken_path }}'

# Production settings, with authentication and security turned on
# portal_backend_env:
#   PORTAL_DB_URL: "{{ portal_db_jdbc_url }}"
#   PORTAL_DB_SCHEMA: "public"
#   PORTAL_DB_USER: "{{ portal_db_user }}"
#   PORTAL_DB_PASSWORD: "{{ portal_db_password }}"
#   META_DB_URL: "{{ meta_db_jdbc_url }}"
#   META_DB_SCHEMA: "public"
#   META_DB_USER: "{{ meta_db_user }}"
#   META_DB_PASSWORD:  "{{ meta_db_password }}"
#   SCIENCE_DB_URL: "{{ science_db_jdbc_url }}"
#   SCIENCE_DB_SCHEMA: "public"
#   SCIENCE_DB_MAIN_TABLE: "adni_merge"
#   SCIENCE_DB_USER: "{{ science_db_user }}"
#   SCIENCE_DB_PASSWORD: "{{ science_db_password }}"
#   AUTHENTICATION: 1
#   CLIENT_ID: '{{ portal_backend_hbp_client_id }}'
#   CLIENT_SECRET: '{{ portal_backend_hbp_client_secret }}'
#   TOKEN_URI: '{{ portal_backend_hbp_access_token_uri }}'
#   AUTH_URI: '{{ portal_backend_hbp_user_authorization_uri }}'
#   USER_INFO_URI: '{{ portal_backend_hbp_user_info_uri }}'
#   LOGGING_LEVEL_WEB: '{{ portal_backend_logging_level_web }}'
#   LOGGING_LEVEL_HIBERNATE: '{{ portal_backend_logging_level_hibernate }}'
#   CONTEXT_PATH: '{{ portal_backend_context_path }}'
#   SESSION_TIMEOUT: '{{ portal_backend_session_timeout }}'
#   WOKEN_URL: '{{ internal_woken_url }}'
#   EXAREME_URL: '{{ portal_backend_exareme_url }}'
#   FRONTEND_LOGIN_URL: '{{ portal_backend_frontend_login_url }}'
#   FRONTEND_AFTER_LOGIN_URL: '{{ portal_backend_frontend_after_login_url }}'
#   FRONTEND_AFTER_LOGOUT_URL: '{{ portal_backend_frontend_after_logout_url }}'
