---

portal_backend_marathon_id: /portal-backend

portal_backend_port: 8080
portal_backend_contextPath: "/services"

portal_backend_version: 0.0.1-SNAPSHOT
portal_backend_jar: "backend-services-{{ portal_backend_version }}.jar"

portal_backend_dir: "/home/mip/backend"
portal_backend_config_dir: "{{ portal_backend_dir}}/config"
portal_backend_user: mip
portal_backend_group: mip

portal_db_port: 31432
portal_db_host: localhost
portal_db_user: postgres
portal_db_password: postgres
portal_db_jdbc_url: "jdbc:postgresql://{{ analytics_db_host }}:{{ analytics_db_port }}/postgres"
portal_db_jdbc_driver: "org.postgresql.Driver"
portal_db_marathon_id: "/portaldb"

portal_backend_security_enabled: false

#portal_backend_hbp_clientId:
#portal_backend_hbp_clientSecret:
portal_backend_hbp_accessTokenUri: "https://services.humanbrainproject.eu/oidc/token"
portal_backend_hbp_userAuthorizationUri: "https://services.humanbrainproject.eu/oidc/authorize"
portal_backend_hbp_userInfoUri: "https://services.humanbrainproject.eu/oidc/userinfo"
portal_backend_hbp_use_current_uri: false
portal_backend_hbp_pre_established_redirect_uri: "https://mip.humanbrainproject.eu/services/login/hbp"

portal_backend_logging_level_security: "DEBUG"
