---

- include: marathon.yml
  when: i2b2_db_deploy

- name: Install Python psycopg2 module for Postgres (required by postgresql_db task), pip and curl
  apt: name={{ item }} state=present
  with_items: '{{ i2b2_db_deb_packages }}'
  when: ansible_os_family == 'Debian'
  delegate_to: "{{ groups['control'][0] }}"
  become: True

# See https://github.com/anarcher/ansible-docker-registry/issues/1
- name: Make sure pip upgraded
  command: easy_install -U pip
  when: ansible_os_family == 'Debian'
  delegate_to: "{{ groups['control'][0] }}"
  become: True

- name: Install Python module for Docker (required by docker_container task)
  pip: name=docker-py state=present
  delegate_to: "{{ groups['control'][0] }}"

# run this task on the database host
- name: Wait for the i2b2 database to be up and running
  wait_for: >
    port="{{ i2b2_db_port }}"
    delay=2

- name: Drop database with name "i2b2"
  postgresql_db:
    name: "{{ i2b2_db_name }}"
    port: "{{ i2b2_db_port }}"
    login_host: "{{ i2b2_db_host }}"
    login_user: "{{ i2b2_db_admin_user }}"
    login_password: "{{ i2b2_db_admin_password }}"
    state: absent
  delegate_to: "{{ groups['control'][0] }}"
  when: (not i2b2_db_deploy) and i2b2_db_cleanup

- name: Create a new database with name "i2b2"
  postgresql_db:
    name: "{{ i2b2_db_name }}"
    port: "{{ i2b2_db_port }}"
    login_host: "{{ i2b2_db_host }}"
    login_user: "{{ i2b2_db_admin_user }}"
    login_password: "{{ i2b2_db_admin_password }}"
    state: present
  delegate_to: "{{ groups['control'][0] }}"

- name: Create i2b2 user
  postgresql_user:
    login_host: "{{ i2b2_db_host }}"
    login_user: "{{ i2b2_db_admin_user }}"
    login_password: "{{ i2b2_db_admin_password }}"
    db: "{{ i2b2_db_name }}"
    port: "{{ i2b2_db_port }}"
    name: "{{ i2b2_db_user }}"
    password: "{{ i2b2_db_password }}"
    role_attr_flags: "SUPERUSER"
  delegate_to: "{{ groups['control'][0] }}"

- name: Create group for Airflow
  group:
    name: '{{ airflow_group }}'
    state: present

- name: Create user for Airflow
  user:
    name: '{{ airflow_user }}'
    group: '{{ airflow_group }}'
    home: '{{ airflow_home }}'

- name: Create airflow home
  file:
    path: '{{ airflow_home}}'
    state: directory
    owner: '{{ airflow_user }}'

- name: Run Alembic migration
  docker_container:
    name: migrate_i2b2_db
    image: "{{ i2b2_setup_image }}:{{ i2b2_setup_version }}"
    command: upgrade head
    detach: no
    network_mode: host
    interactive: yes
    # cleanup: yes
    env:
      DB_URL: "{{ i2b2_db_sql_alchemy_conn }}"
  delegate_to: "{{ groups['control'][0] }}"
