---

dependencies:
  #- docker
  - role: dummy-hosts
    dummy_dns_items:
      - ip: "{{ docker_registry_ip }}"
        dns: "{{ docker_registry_dns }}"
    when: docker_registry_ip is defined and docker_registry_dns is defined
