---
# default is etc/utc in build 20141129 [http://cloud.centos.org/centos/7/images/]
- name: Set timezone to etc/utc
  become: yes
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: yes

# add hosts to /etc/hosts
- name: Configure hosts file
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].private_ipv4 }} {{ item }}{% if use_host_domain %} {{ item }}.{{ host_domain }}{% endif %}$"
    line: "{{ hostvars[item].private_ipv4 }} {{ item }}{% if use_host_domain %} {{ item }}.{{ host_domain}}{% endif %}"
    state: present
  when: hostvars[item].private_ipv4 is defined
  with_items: "{{ groups['all'] }}"

- name: Clean hosts file
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item }}"
    state: absent
  with_items:
    - '^127\.0\.\d+\.\d+(\s+)(?i){{ inventory_hostname }}.*'
    - '^::1(\s+)(?i){{ inventory_hostname }}.*'

- name: Ping APT proxy
  wait_for:
    host: "{{ apt_proxy_host}}"
    port: "{{ apt_proxy_port}}"
    connect_timeout: 2
    timeout: 5
  register: apt_proxy_status
  ignore_errors: true
  when: apt_proxy_host is defined

- debug: 'msg={{apt_proxy_status.state}}'

- template:
    src: apt-proxy.j2
    dest: /etc/apt/apt.conf.d/01proxy
  when: apt_proxy_host is defined and apt_proxy_status.state == 'started'

- file: path='/etc/apt/apt.conf.d/01proxy' state='absent'
  when: apt_proxy_host is not defined or apt_proxy_status.state != 'started'
