---

- name: Should ldsm-db be deployed in its own Postgres server?
  set_fact:
    do_ldsm_db_deploy: "{{ ldsm_db_deploy | bool }}"

- include: marathon.yml
  when: do_ldsm_db_deploy

# run this task on the database host
- name: Wait for the LDSM database to be up and running
  wait_for: >
    port="{{ ldsm_db_port }}"
    delay=2

- name: Drop database with name "ldsm"
  postgresql_db:
    name: "{{ ldsm_db_name }}"
    port: "{{ ldsm_db_port }}"
    login_host: "{{ ldsm_db_host }}"
    login_user: "{{ ldsm_db_admin_user }}"
    login_password: "{{ ldsm_db_admin_password }}"
    state: absent
  delegate_to: "{{ groups['control'][0] }}"
  when: (not do_ldsm_db_deploy) and ldsm_db_cleanup

- name: Create a new database with name "ldsm"
  postgresql_db:
    name: "{{ ldsm_db_name }}"
    port: "{{ ldsm_db_port }}"
    login_host: "{{ ldsm_db_host }}"
    login_user: "{{ ldsm_db_admin_user }}"
    login_password: "{{ ldsm_db_admin_password }}"
    state: present
  delegate_to: "{{ groups['control'][0] }}"

- name: Create ldsm user
  postgresql_user:
    login_host: "{{ ldsm_db_host }}"
    login_user: "{{ ldsm_db_admin_user }}"
    login_password: "{{ ldsm_db_admin_password }}"
    db: "{{ ldsm_db_name }}"
    port: "{{ ldsm_db_port }}"
    name: "{{ ldsm_db_user }}"
    password: "{{ ldsm_db_password }}"
    role_attr_flags: "SUPERUSER"
  delegate_to: "{{ groups['control'][0] }}"

- name: Log into private Docker registries
  docker_login:
    username: '{{ item.username }}'
    password: '{{ item.password }}'
    registry_url: '{{ item.url }}'
  with_items: "{{ ldsm_db_docker_registries }}"
  no_log: true

- name: Setup LDSM database
  docker_container:
    name: setup_ldsm_db
    image: "{{ item.image }}"
    command: "{{ item.command | default(ommit) }}"
    env: "{{ item.env }}"
    detach: no
    network_mode: host
    interactive: yes
    cleanup: yes
  with_items: "{{ ldsm_db_docker_setup }}"
  delegate_to: "{{ groups['control'][0] }}"
