---

- hosts: analytics-db
  become: yes
  gather_facts: no
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  roles:

    - role: analytics-database
      tags: ['analytics-database', 'analytics-db', 'database', 'analytics', 'marathon-app']

    - role: audit-deployment
      installed_component: analytics-database
      tags: ['analytics-database', 'analytics-db', 'database', 'analytics', 'marathon-app']
