---

- hosts: chronos
  become: yes
  gather_facts: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/zookeeper.yml"
    - "{{ play_dir }}/vars/infrastructure/mesos.yml"
    - "{{ play_dir }}/vars/algorithm-factory/endpoints.yml"
    - "{{ play_dir }}/vars/algorithm-factory/chronos.yml"

  roles:

    - role: chronos
      tags: ['chronos', 'analytics', 'algorithm-factory', 'af', 'marathon-app']

    - role: audit-deployment
      installed_component: algorithm-factory-chronos
      tags: ['chronos', 'analytics', 'algorithm-factory', 'af', 'marathon-app']
