---

postgres_marathon_id: /postgres

postgres_data_dir: /srv/docker/postgres/data
# The user running the Docker container for Postgres, default to '999' (postgres user in the Postgres docker container)
postgres_docker_user: '999'

# Pin the database to a particular host as it needs to store its files in a known place
postgres_marathon_host: '{{ inventory_hostname }}'
# Port exposed by Marathon, must be in the range [31000,32000[
postgres_port: 31432

postgres_version: "9.4.5"

postgres_user: postgres
#postgres_password: TO FILL

# URL to marathon master internal to the current cluster. You need to ensure that Ansible can reach that URL.
internal_marathon_url: http://localhost:5080

# Attach the Postgres database to a particular host. The hostname should be the name known by Marathon / Mesos
#postgres_marathon_host:
