---

- name: Should data-catalog-db be deployed in its own Postgres server?
  set_fact:
    do_data_catalog_db_deploy: "{{ data_catalog_db_deploy | bool }}"

- include: marathon.yml
  when: do_data_catalog_db_deploy

# run this task on the database host
- name: Wait for the Data Catalog database to be up and running
  wait_for: >
    port="{{ data_catalog_db_port }}"
    delay=2

- name: Drop database with name "data_catalog"
  postgresql_db:
    name: "{{ data_catalog_db_name }}"
    port: "{{ data_catalog_db_port }}"
    login_host: "{{ data_catalog_db_host }}"
    login_user: "{{ data_catalog_db_admin_user }}"
    login_password: "{{ data_catalog_db_admin_password }}"
    state: absent
  delegate_to: "{{ groups['control'][0] }}"
  when: (not do_data_catalog_db_deploy) and data_catalog_db_cleanup

- name: Create a new database with name "data_catalog"
  postgresql_db:
    name: "{{ data_catalog_db_name }}"
    port: "{{ data_catalog_db_port }}"
    login_host: "{{ data_catalog_db_host }}"
    login_user: "{{ data_catalog_db_admin_user }}"
    login_password: "{{ data_catalog_db_admin_password }}"
    state: present
  delegate_to: "{{ groups['control'][0] }}"

- name: Create data_catalog user
  postgresql_user:
    login_host: "{{ data_catalog_db_host }}"
    login_user: "{{ data_catalog_db_admin_user }}"
    login_password: "{{ data_catalog_db_admin_password }}"
    db: "{{ data_catalog_db_name }}"
    port: "{{ data_catalog_db_port }}"
    name: "{{ data_catalog_db_user }}"
    password: "{{ data_catalog_db_password }}"
    role_attr_flags: "SUPERUSER"
  delegate_to: "{{ groups['control'][0] }}"

- name: Setup Data catalog database using Alembic migration
  docker_container:
    name: setup_data_catalog_db
    image: "{{ data_catalog_db_setup_image }}"
    command: upgrade head
    detach: no
    network_mode: host
    interactive: yes
    cleanup: yes
    env:
      DB_URL: "{{ data_catalog_db_sql_alchemy_conn }}"
  delegate_to: "{{ groups['control'][0] }}"
