---

- name: Wait for Marathon
  include: ../../marathon-app/tasks/wait-for-marathon.yml
  vars:
    uri: "{{ internal_marathon_url }}"

- name: Remove old Portal backend using Marathon
  marathon_app:
    uri: "{{ internal_marathon_url }}"
    id: "{{ portal_backend_marathon_id }}"
    state: "absent"
    wait_timeout: 600
  async: 600
  poll: 1
  delegate_to: "{{ groups['control'][0] }}"
  run_once: true

- name: Launch Portal backend using Marathon
  marathon_app:
    uri: "{{ internal_marathon_url }}"
    id: "{{ portal_backend_marathon_id }}"
    state: "present"
    docker_image: "hbpmip/portal-backend:{{ portal_backend_version }}"
    docker_force_pull_image: true
    docker_network: BRIDGE
    docker_port_mappings:
      - hostPort: "{{ portal_backend_port }}"
        containerPort: 8080
        name: 'http'
      - hostPort: "{{ portal_backend_akka_port }}"
        containerPort: 4089
        name: 'akka'
    docker_parameters: '{{ portal_backend_docker_parameters }}'
    env: '{{ portal_backend_env }}'
    instances: '{{ portal_backend_instances }}'
    cpus: '{{ portal_backend_cpus }}'
    mem: '{{ portal_backend_mem }}'
    ports: []
    require_ports: true
    constraints: '{{ portal_backend_marathon_constraints }}'
    dependencies: ["{{ portal_db_marathon_id }}"]
    executor: ""
    wait_timeout: 600
    health_checks:
      - protocol: HTTP
        port: '{{ portal_backend_port }}'
        path: '{{ portal_backend_context_path }}/health'
        gracePeriodSeconds: 300
        intervalSeconds: 60
        timeoutSeconds: 20
        maxConsecutiveFailures: 2
    upgrade_strategy:
      minimumHealthCapacity: 0
      maximumOverCapacity: 0
  async: 600
  poll: 1
  delegate_to: "{{ groups['control'][0] }}"
  run_once: true
