---

# Complete the installation of Ansible by installing required software on the local computer

- hosts: localhost
  become: yes

  vars:
    git_crypt_rhel_download_url: "https://drive.switch.ch/index.php/s/Y2u46cPUartTGp8/download"

  tasks:

    # Install git-crypt
    - name: Add PPA ppa:avacariu/git-crypt for Ubuntu 14.04
      apt_repository: repo='ppa:avacariu/git-crypt'
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_version | version_compare('15.10', 'lt'))

    - name: "Install git-crypt, required to read protected configuration files in this Ansible project"
      apt: name=git-crypt state=present
      when: ansible_distribution == "Ubuntu"

    - name: "Install git-crypt, required to read protected configuration files in this Ansible project"
      apt: name=git-crypt state=present
      when: ansible_distribution == "Ubuntu"

    - name: Download Git-crypt excutable for RedHat
      get_url:
        url: "{{ git_crypt_rhel_download_url }}"
        dest: /tmp/git-crypt-RHEL.tar.xz
      when: ansible_distribution == "RedHat"

    - name: Unzip Git crypt
      unarchive:
        src: /tmp/git-crypt-RHEL.tar.xz
        dest: /usr/local/bin/
      when: ansible_distribution == "RedHat"
