
#- hosts: control
#  vars_files:
#    - "{{ play_dir }}/vars/common.yml"
#    - "{{ play_dir }}/vars/versions.yml"

    # TODO: Stop and destroy all applications

- hosts: mesos-follower
  serial: "{{ serial | default(1) }}"
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  tasks:

    - name: Set default value for skipped_roles
      set_fact:
        skipped_roles: []
      when: skipped_roles is not defined

    - name: Stop all services
      service:
        name: '{{ item }}'
        state: stopped
      with_items:
        - mesos-slave
        - "{% if 'docker' not in skipped_roles %}docker{% endif %}"

    - name: Cleanup logs and working directories
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /var/lib/mesos/meta/slaves/latest
        - /var/log/mesos/

    - name: Destroy Mesos work dir
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /var/lib/mesos/
      when: reset_mesos is defined and reset_mesos

- hosts: mesos-mixed
  serial: "{{ serial | default(1) }}"
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  tasks:

    - name: Set default value for skipped_roles
      set_fact:
        skipped_roles: []
      when: skipped_roles is not defined

    - name: Stop all services
      service:
        name: '{{ item }}'
        state: stopped
      with_items:
        - marathon
        - mesos-slave
        - mesos-master
        - zookeeper
        - "{% if 'docker' not in skipped_roles %}docker{% endif %}"

    - name: Cleanup logs and working directories
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /var/lib/mesos/meta/slaves/latest
        - /var/log/mesos/
        - /var/log/zookeeper/zookeeper.log

    - name: Destroy Zookeeper redo log and Mesos work dir
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /var/lib/mesos/
        - /var/lib/zookeeper/
        - /var/log/zookeeper/
      when: reset_mesos is defined and reset_mesos

- hosts: mesos-leader
  serial: "{{ serial | default(1) }}"
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  tasks:

    - name: Set default value for skipped_roles
      set_fact:
        skipped_roles: []
      when: skipped_roles is not defined

    - name: Stop all services
      service:
        name: '{{ item }}'
        state: stopped
      with_items:
        - marathon
        - mesos-master
        - zookeeper

    - name: Cleanup logs and working directories
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /var/lib/mesos/meta/slaves/latest
        - /var/log/mesos/
        - /var/log/zookeeper/zookeeper.log

    - name: Destroy Zookeeper redo log and Mesos work dir
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /var/lib/mesos/
        - /var/lib/zookeeper/
        - /var/log/zookeeper/
      when: reset_mesos is defined and reset_mesos

- hosts: mesos-follower
  serial: "{{ serial | default(1) }}"
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  tasks:

    - name: Set default value for skipped_roles
      set_fact:
        skipped_roles: []
      when: skipped_roles is not defined

    - name: Restore directories
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - /var/log/mesos/
        - /var/lib/mesos/

    - name: Restart the services
      service:
        name: '{{ item }}'
        state: started
      with_items:
        - "{% if 'docker' not in skipped_roles %}docker{% endif %}"
        - mesos-slave

- hosts: mesos-mixed
  serial: "{{ serial | default(1) }}"
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  tasks:

    - name: Set default value for skipped_roles
      set_fact:
        skipped_roles: []
      when: skipped_roles is not defined

    - name: Restore Mesos directories
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - /var/log/mesos/
        - /var/lib/mesos/

    - name: Restore Zookeeper directories
      file:
        path: '{{ item }}'
        state: directory
        owner: zookeeper
        group: zookeeper
      with_items:
        - /var/log/zookeeper/
        - /var/lib/zookeeper/

    - name: Restart all services
      service:
        name: '{{ item }}'
        state: started
      with_items:
        - "{% if 'docker' not in skipped_roles %}docker{% endif %}"
        - zookeeper
        - mesos-master
        - mesos-slave
        - marathon

- hosts: mesos-leader
  serial: "{{ serial | default(1) }}"
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  tasks:

    - name: Set default value for skipped_roles
      set_fact:
        skipped_roles: []
      when: skipped_roles is not defined

    - name: Restore Mesos directories
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - /var/log/mesos/
        - /var/lib/mesos/

    - name: Restore Zookeeper directories
      file:
        path: '{{ item }}'
        state: directory
        owner: zookeeper
        group: zookeeper
      with_items:
        - /var/log/zookeeper/
        - /var/lib/zookeeper/

    - name: Restart all services
      service:
        name: '{{ item }}'
        state: started
      with_items:
        - zookeeper
        - mesos-master
        - marathon
