---

#
# Setup mesos-leader on one or several servers.
# Requires: zookeeper installed on the same or some other servers.
#
# The following components are optional:
# * marathon: use --skip-tags=marathon
# * mesos-ui: use --skip-tags=mesos-ui
#

- hosts: mesos-leader
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  pre_tasks:
    - name: Install curl
      apt: name=curl state=present

    - name: Set default value for skipped_roles
      set_fact:
        skipped_roles: []
      when: skipped_roles is not defined

  roles:

    - role: mesos
      mesos_zk_dns: "{{ groups.zookeeper | join(',') }}"
      mesos_mode: "leader"
      mesos_leaders_group: "mesos-leader"
      tags: ['mesos', 'container-platforms']

    # Java 8 is required for Marathon
    - role: openjdk
      tags: ['mesos-frameworks', 'marathon', 'runtimes']
      when: "'marathon' not in skipped_roles"

    - role: marathon
      marathon_env_vars:
        - "JAVA_OPTS=-Xmx512m"
      tags: ['mesos-frameworks', 'marathon']
      when: "'marathon' not in skipped_roles"

    #- role: mesos-ui
    #  marathon_env_vars:
    #    - "JAVA_OPTS=-Xmx512m"
    #  tags: ['mesos-frameworks', 'mesos-ui']
    #  when: "'mesos-ui' not in skipped_roles"

    - role: audit-deployment
      installed_component: mesos-leader
      tags: ['mesos', 'container-platforms']
