---

#
# Setup the authenticated reverse proxy for mesos-ui, marathon and other services.
#

- hosts: reverse-proxy
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/algorithm-factory/endpoints.yml"
    - "{{ play_dir }}/vars/data-factory/endpoints.yml"
    - "{{ play_dir }}/vars/web-analytics/endpoints.yml"
    - "{{ play_dir }}/vars/web-analytics/portal-frontend.yml"
    - "{{ play_dir }}/vars/web-analytics/portal-backend.yml"

  roles:

    - role: reverse-proxy
      tags: ['mesos', 'reverse-proxy', 'infra', 'infrastructure']
