---

- hosts: zookeeper
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/zookeeper.yml"

  roles:

    # Java 8 is required for Zookeeper
    - role: openjdk
      tags: ['openjdk', 'zookeeper', 'mesos-frameworks', 'runtimes', 'infra', 'infrastructure']

    - role: zookeeper
      tags: ['zookeeper', 'runtimes', 'infra', 'infrastructure']

    - role: audit-deployment
      installed_component: infrastructure-zookeeper
      tags: ['zookeeper', 'runtimes', 'infra', 'infrastructure']
