---

- hosts: ldsm-db,ldsm-database
  become: yes
  gather_facts: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/mesos.yml"
    - "{{ play_dir }}/vars/hospital-database/endpoints.yml"
    - "{{ play_dir }}/vars/hospital-database/ldsm-database.yml"

  roles:

    - role: ldsm-database
      tags: ['database', 'ldsm-database', 'ldsm-db', 'hospital-database', 'marathon-app']

    - role: audit-deployment
      installed_component: hospital-database-ldsm
      tags: ['ldsm-database', 'ldsm-db', 'hospital-database', 'marathon-app']
