---

- hosts: ldsm-db
  become: yes
  gather_facts: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/mesos.yml"
    - "{{ play_dir }}/vars/hospital-database/endpoints.yml"
    - "{{ play_dir }}/vars/hospital-database/ldsm-database.yml"

  pre_tasks:

    - name: Need to add pre-defined datasets to LDSM?
      set_fact:
        ldsm_add_predefined_datasets: "{{ setup_research_datasets is defined and setup_research_datasets != '' and features_from == 'ldsm-db' }}"
      tags: ['database', 'ldsm-database', 'ldsm-db', 'hospital-database', 'marathon-app']

    - name: Setup predefined datasets into LDSM
      include_vars: "{{ play_dir }}/vars/hospital-database/{{ setup_research_datasets }}-ldsm-datasets.yml"
      when: ldsm_add_predefined_datasets
      tags: ['database', 'ldsm-database', 'ldsm-db', 'hospital-database', 'marathon-app']

    - name: Add predefined data to ldsm setup
      set_fact:
        ldsm_db_docker_setup: "{{ predefined_ldsm_db_docker_setup | union(ldsm_db_docker_setup | default([])) }}"
      when: ldsm_add_predefined_datasets
      tags: ['database', 'ldsm-database', 'ldsm-db', 'hospital-database', 'marathon-app']

  roles:

    - role: ldsm-database
      tags: ['database', 'ldsm-database', 'ldsm-db', 'hospital-database', 'marathon-app']

    - role: audit-deployment
      installed_component: hospital-database-ldsm
      tags: ['ldsm-database', 'ldsm-db', 'hospital-database', 'marathon-app']
