---

- hosts: ldsm-db,ldsm-database
  become: yes
  gather_facts: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/mesos.yml"
    - "{{ play_dir }}/vars/hospital-database/endpoints.yml"
    - "{{ play_dir }}/vars/hospital-database/ldsm-database.yml"

  pre_tasks:

    - name: Setup standard research datasets into LDSM
      include_vars: "{{ play_dir }}/vars/reference/standard-research-datasets.yml"
      when: setup_standard_research_datasets is defined and setup_standard_research_datasets == 'ldsm-db'
      tags: ['ldsm-database', 'research-db', 'database', 'reference', 'marathon-app']

    - name: Add standard research datasets to research database setup
      set_fact:
        ldsm_db_docker_setup: "{{ standard_research_db_docker_setup | union(ldsm_db_docker_setup | default([])) }}"
      when: setup_standard_research_datasets is defined and setup_standard_research_datasets == 'ldsm-db'
      tags: ['ldsm-database', 'research-db', 'database', 'reference', 'marathon-app']

  roles:

    - role: ldsm-database
      tags: ['database', 'ldsm-database', 'ldsm-db', 'hospital-database', 'marathon-app']

    - role: audit-deployment
      installed_component: hospital-database-ldsm
      tags: ['ldsm-database', 'ldsm-db', 'hospital-database', 'marathon-app']
