---

- hosts: postgresraw-ui
  become: yes
  gather_facts: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/mesos.yml"
    - "{{ play_dir }}/vars/hospital-database/endpoints.yml"
    - "{{ play_dir }}/vars/hospital-database/postgresraw-ui.yml"

  roles:

    - role: postgresraw-ui
      tags: ['postgresraw-ui', 'ldsm-database', 'ldsm-db', 'hospital-database', 'marathon-app']

    - role: audit-deployment
      installed_component: hospital-database-postgresraw-ui
      tags: ['ldsm-database', 'ldsm-db', 'hospital-database', 'marathon-app']
